# Generated by Django 5.2 on 2025-04-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='companyName',
            field=models.CharField(max_length=250),
        ),
    ]
