# Generated by Django 5.2 on 2025-04-19 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_jobpost_companyname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateapplication',
            unique_together={('user', 'job')},
        ),
    ]
