# Generated by Django 5.2 on 2025-04-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_candidateapplication_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost'),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
