# Generated by Django 5.2 on 2025-04-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_candidateapplication_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedcandidate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateapplication'),
        ),
    ]
